apiVersion: v1
kind: Service
metadata:
  name: {{ include "wp-rock-sre.fullname" . }}-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wp-rock-sre.fullname" . }}-db-pvc
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ include "wp-rock-sre.fullname" . }}-mysql
  labels:
    app: wordpress
spec:
  replicas: {{ .Values.dbReplicaCount }}
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wp-rock-sre.fullname" . }}-mysql-passwd
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "wp-rock-sre.fullname" . }}-db-pvc
