apiVersion: v2
name: wp-rock-sre
description: A Helm chart for WP Site with MySQL db
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: nginx
    condition: nginx.enabled

  - name: wordpress-mysql 
    condition: wordpress-mysql.enabled

  - name: wordpress-sre
    condtion: wordpress-sre.enabled


