nginx:
  enabled: true 

#wordpress database server
wordpress-mysql:
  enabled: true

  image:
    repository: mysql
    pullPolicy: Always
    tag: 5.7

  resources: 
    limits:
      cpu: 100m
      memory: 158Mi
    requests:
      cpu: 100m
      memory: 158Mi

#wordpress site
wordpress-sre:
  enabled: true
  image:
    repository: kungus/wp-sre
    pullPolicy: Always
    tag: 1.0.1

  service:
    type: LoadBalancer
    port: 80

#main chart's vals
nameOverride: ""
fullnameOverride: ""



