apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress-mysql.name" . }}
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi