apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-mysql.name" . }}
  labels:
    {{- include "wordpress-mysql.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: mysql
  selector:
    {{- include "wordpress-mysql.selectorLabels" . | nindent 4 }}
