apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress-sre.fullname" . }}
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi