apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "nginx.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: grafana.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana-release
          servicePort: 3000
  - host: wordpress.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress-sre
          servicePort: 8080
