apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: grafana.minikube.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-release
                port:
                  number: 80
    - host: wordpress.minikube.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-sre
                port:
                  number: 8080